# Generated by Django 5.1.5 on 2025-01-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_ordering', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dishes',
        ),
    ]
